"""
Report Generator for Q-LIFELOCK.
Produces Executive Markdown reports and CSV finding exports.
"""
import io
import csv
from datetime import datetime, timezone
from core.domain.models import ScanSummary


class ReportGenerator:
    """Generates human-readable Executive Markdown reports and CSV data."""

    @staticmethod
    def to_csv(scan_summary: ScanSummary) -> str:
        """Export all findings to CSV format."""
        output = io.StringIO()
        writer = csv.writer(output)
        
        headers = [
            "Finding ID",
            "Algorithm",
            "Function",
            "Priority",
            "Risk Score",
            "Data Lifetime (Years)",
            "Lifetime Category",
            "Data Sensitivity",
            "Usage Context",
            "Recommended PQC Target",
            "Migration Status",
            "File Path",
            "Line Number",
            "Evidence",
            "Rationale",
        ]
        writer.writerow(headers)

        for f in scan_summary.findings:
            writer.writerow([
                f.finding_id,
                f.algorithm.value,
                f.function.value,
                f.priority.value,
                f"{f.risk_score:.1f}",
                f.data_lifetime_years if f.data_lifetime_years is not None else "N/A",
                f.data_lifetime_category.value,
                f.data_sensitivity.value,
                f.usage_context.value,
                f.recommended_pqc_target.value if f.recommended_pqc_target else "N/A",
                f.migration_status.value,
                f.file_path,
                f.line_number,
                f.evidence.line_content.strip()[:100],
                f.priority_reason,
            ])

        return output.getvalue()

    @staticmethod
    def to_markdown_executive_summary(scan_summary: ScanSummary) -> str:
        """Export an executive-ready quantum risk and migration report in Markdown."""
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        critical_findings = [f for f in scan_summary.findings if f.priority.value == "CRITICAL"]
        high_findings = [f for f in scan_summary.findings if f.priority.value == "HIGH"]

        md = f"""# Q-LIFELOCK Executive Quantum Readiness Report

**Generated:** {now_str}  
**Target Repository:** `{scan_summary.repository_path}`  
**CRQC Threat Scenario Year:** {scan_summary.scenario_year}  
**Overall Quantum Readiness Score:** **{scan_summary.readiness_score:.1f}%**  

---

## 1. Executive Summary

Q-LIFELOCK performed a cryptographic inventory scan and Harvest-Now-Decrypt-Later (HNDL) exposure analysis against `{scan_summary.repository_path}`.

- **Total Files Scanned:** {scan_summary.total_files_scanned}
- **Total Cryptographic Findings:** {scan_summary.total_findings}
- **Critical Exposure Assets:** {scan_summary.critical_count}
- **High Exposure Assets:** {scan_summary.high_count}
- **Medium Exposure Assets:** {scan_summary.medium_count}
- **Low Exposure Assets:** {scan_summary.low_count}

Under the evaluated **{scan_summary.scenario_year} Cryptographically Relevant Quantum Computer (CRQC)** threat horizon:
- Assets with required data lifetimes extending past {scan_summary.scenario_year} face **active HNDL risk** today. Adversaries capturing encrypted ciphertext now can decrypt it once quantum cryptanalysis becomes operational.

---

## 2. Immediate Migration Priorities (Critical & High Risk)

| Finding ID | Algorithm | Function | Lifetime | PQC Recommendation (NIST FIPS) | Location |
|---|---|---|---|---|---|
"""
        for f in critical_findings + high_findings:
            pqc = f.recommended_pqc_target.value if f.recommended_pqc_target else "N/A"
            lifetime = f"{f.data_lifetime_years} yrs" if f.data_lifetime_years else "Unknown"
            md += f"| `{f.finding_id}` | **{f.algorithm.value}** | {f.function.value} | {lifetime} | `{pqc}` | `{f.file_path}:{f.line_number}` |\n"

        md += f"""
---

## 3. Post-Quantum Cryptography Migration Strategy

Based on NIST finalized standards (August 2024):
1. **Key Encapsulation / Key Exchange (FIPS 203):** Replace RSA key exchange and ECDH with **ML-KEM-768** (or Hybrid ECDH + ML-KEM).
2. **Digital Signatures & Authentication (FIPS 204):** Replace RSA signatures and ECDSA with **ML-DSA-65**.
3. **High-Assurance / Firmware Signing (FIPS 205):** Use state-independent hash-based **SLH-DSA** where mathematical reliance on lattice hardness is undesirable.

---
*Report automatically generated by Q-LIFELOCK.*
"""
        return md
